spring:
  application:
    name: test-firestore
  cache:
    cache-names:
    - users
    caffeine:
      spec: "maximumSize=500,expireAfterWrite=600s"
  # cloud:
  #   gcp:
  #     firestore:
  #       emulator:
  #         enabled: true
  profiles:
    active:
    - dev

spring.sleuth.sampler.probability: 1.0
spring.sleuth.web.skipPattern: (^cleanup.*|.+favicon.*)

